print("Twinkle,twinkle,little star,\n")
print("\thow are wonder what you are!\n")
print("\t\tup above the world so high,\n")
print("\t\tlike a diamond in the sky,\n")
print("Twinkle,tiwnkle,little star,\n")
print("\thow i wonder what you are")
